### ISSUE TITLE
HTTP Error 412: Precondition Failed

### ISSUE THREAD

**Issue by Junxi-Chen** [johnshazhu/114_register#1]
非常感谢作者的工作。
当我在使用的时候，返回HTTP Error 412: Precondition Failed。应该是之前的路径被封锁了，望修复，感谢

**Comment by johnshazhu** [comment]
> 非常感谢作者的工作。 当我在使用的时候，返回HTTP Error 412: Precondition Failed。应该是之前的路径被封锁了，望修复，感谢

某一个接口，还是初始就不能用了？

**Comment by Junxi-Chen** [comment]
> > 非常感谢作者的工作。 当我在使用的时候，返回HTTP Error 412: Precondition Failed。应该是之前的路径被封锁了，望修复，感谢
> 
> 某一个接口，还是初始就不能用了？

是初始就不能用了，我是用Reqabel补获的Cookie

**Comment by johnshazhu** [comment]
> > > 非常感谢作者的工作。 当我在使用的时候，返回HTTP Error 412: Precondition Failed。应该是之前的路径被封锁了，望修复，感谢
> > 
> > 
> > 某一个接口，还是初始就不能用了？
> 
> 是初始就不能用了，我是用Reqabel补获的Cookie

好的，我晚点儿看下

**Comment by Junxi-Chen** [comment]
非常感谢🙏

**Comment by johnshazhu** [comment]
> 非常感谢🙏

抱歉啊，114公众号升级后，接口访问时加上了一个HKNCYzbu的加密参数，这个暂时无能为力了

**Comment by Junxi-Chen** [comment]
收到，还是谢谢作者！

**Comment by hhcol620** [comment]
现在还好用吗
